# Generated by Django 4.1.2 on 2022-10-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_songvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='link',
            field=models.CharField(default='', max_length=90),
        ),
    ]
