# Generated by Django 4.1.1 on 2022-09-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'ContactUs(requests)', 'verbose_name_plural': 'People requests(contacts)'},
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='message',
            new_name='request',
        ),
        migrations.AddField(
            model_name='contactus',
            name='user',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
